spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #当前数据源的类型
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/dbcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root